package org.openidentity.spring.auth;
import org.openidentity.auth.*;import org.openidentity.core.VerifiedAuthentication;import java.security.*;import java.time.Clock;import java.util.*;
public final class OpenIdentityAuthenticationService {
 public static final String PURPOSE="openidentity.oauth.authenticate";
 private final Oi015Verifier verifier;private final OpenIdentityAuthenticationChallengeStore store;private final byte[] audience;private final Clock clock;private final SecureRandom random;private final long challengeLifetimeSeconds;
 public OpenIdentityAuthenticationService(Oi015Verifier verifier,OpenIdentityAuthenticationChallengeStore store,byte[] audience,Clock clock,SecureRandom random,long challengeLifetimeSeconds){this.verifier=Objects.requireNonNull(verifier);this.store=Objects.requireNonNull(store);this.audience=audience.clone();this.clock=Objects.requireNonNull(clock);this.random=Objects.requireNonNull(random);if(challengeLifetimeSeconds<1)throw new IllegalArgumentException("challengeLifetimeSeconds");this.challengeLifetimeSeconds=challengeLifetimeSeconds;}
 public IssuedChallenge issue(byte[] contextHash){if(contextHash==null||contextHash.length!=34)throw new IllegalArgumentException("contextHash");long now=clock.instant().getEpochSecond();byte[] nonce=new byte[32];random.nextBytes(nonce);var c=new OpenIdentityAuthenticationChallenge(audience,PURPOSE,nonce,contextHash,now,now+challengeLifetimeSeconds);return new IssuedChallenge(store.create(c),c);}
 public OpenIdentityNativeAuthenticationToken verify(String challengeId,byte[] securedAssertionBytes){OpenIdentityAuthenticationChallenge c=store.consume(challengeId);if(c==null)throw new IllegalArgumentException("unknown or consumed challenge");long now=clock.instant().getEpochSecond();if(now>=c.expiresAt())throw new IllegalArgumentException("expired challenge");SecuredAuthenticationAssertion secured=Oi015Codec.decode(securedAssertionBytes);VerifiedAuthentication v=verifier.verify(secured,c.audience(),c.purpose(),c.nonce(),c.contextHash(),now);return new OpenIdentityNativeAuthenticationToken(v.identity(),v.assertionId());}
 public record IssuedChallenge(String challengeId,OpenIdentityAuthenticationChallenge challenge){}
}