package org.openidentity.spring.ad;
import org.openidentity.ad.*;import org.openidentity.ad.ldap.*;import org.openidentity.ad.spnego.*;import org.openidentity.core.*;import org.springframework.boot.autoconfigure.*;import org.springframework.boot.autoconfigure.condition.*;import org.springframework.boot.context.properties.EnableConfigurationProperties;import org.springframework.context.annotation.*;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.context.SecurityContextHolderFilter;import java.util.*;

@AutoConfiguration
@ConditionalOnProperty(prefix="openidentity.active-directory",name="enabled",havingValue="true")
@EnableConfigurationProperties(OpenIdentityActiveDirectoryProperties.class)
@EnableWebSecurity
public class OpenIdentityActiveDirectoryAutoConfiguration {
 @Bean SpnegoAcceptor openIdentitySpnegoAcceptor(OpenIdentityActiveDirectoryProperties p){return new SpnegoAcceptor(required(p.getKerberos().getServicePrincipal(),"kerberos.service-principal"),Objects.requireNonNull(p.getKerberos().getKeytab(),"kerberos.keytab"));}
 @Bean AdPrincipalResolver openIdentityAdPrincipalResolver(OpenIdentityActiveDirectoryProperties p){var l=p.getLdap();String secret=System.getenv("OPENIDENTITY_LDAP_BIND_PASSWORD");if(secret==null||secret.isEmpty())throw new IllegalStateException("missing OPENIDENTITY_LDAP_BIND_PASSWORD");return new LdapAdPrincipalResolver(new LdapAdPrincipalResolver.Profile(l.getProfileId(),required(l.getHost(),"ldap.host"),l.getPort(),required(l.getBaseDn(),"ldap.base-dn"),required(l.getBindPrincipal(),"ldap.bind-principal"),secret,HexFormat.of().parseHex(required(l.getDirectoryIdHex(),"ldap.directory-id-hex")),true));}
 @Bean FileCanonicalIdentityStateRepository openIdentityStateRepository(OpenIdentityActiveDirectoryProperties p){return new FileCanonicalIdentityStateRepository(Objects.requireNonNull(p.getBindings().getStateDirectory(),"bindings.state-directory"));}
 @Bean InMemoryExternalAdBindingRegistry openIdentityAdBindingRegistry(OpenIdentityActiveDirectoryProperties p){return new InMemoryExternalAdBindingRegistry(Objects.requireNonNull(p.getBindings().getStore(),"bindings.store"));}
 @Bean InMemoryExternalAdBindingRegistry.Policy openIdentityAdPolicy(OpenIdentityActiveDirectoryProperties p,FileCanonicalIdentityStateRepository states){byte[] directory=HexFormat.of().parseHex(required(p.getLdap().getDirectoryIdHex(),"ldap.directory-id-hex"));return new InMemoryExternalAdBindingRegistry.Policy(){public boolean directoryTrusted(byte[] d){return Arrays.equals(d,directory);}public boolean serviceAllowed(byte[] d,String s){return "openidentity-ad-link-service".equals(s);}public boolean mechanismAllowed(byte[] d,int m){return m==ExternalAdBindingV1.KERBEROS_SPNEGO;}public boolean identityActive(byte[] id){var x=states.resolve(id);return x!=null&&x.active();}public long currentAuthenticationGeneration(byte[] id){var x=states.resolve(id);if(x==null)throw new IllegalArgumentException("identity");return x.authenticationAuthority().generation();}};}
 @Bean OpenIdentityActiveDirectoryService openIdentityActiveDirectoryService(AdPrincipalResolver resolver,InMemoryExternalAdBindingRegistry registry,InMemoryExternalAdBindingRegistry.Policy policy,OpenIdentityActiveDirectoryProperties p){return new OpenIdentityActiveDirectoryService(resolver,registry,policy,p.getLdap().getProfileId(),"openidentity-ad-link-service");}
 @Bean SpnegoExchangeProvider openIdentitySpnegoExchangeProvider(SpnegoAcceptor a){return ()->{var x=a.begin();return new SpnegoExchange(){public SpnegoExchange.Result accept(byte[] token){var r=x.accept(token);return new SpnegoExchange.Result(r.established(),r.principal(),r.responseToken());}public void close(){x.close();}};};}
 @Bean OpenIdentitySpnegoAuthenticationFilter openIdentitySpnegoAuthenticationFilter(SpnegoExchangeProvider x,OpenIdentityActiveDirectoryService s){return new OpenIdentitySpnegoAuthenticationFilter(x,s);}
 @Bean @ConditionalOnMissingBean(SecurityFilterChain.class) SecurityFilterChain openIdentityAdSecurityFilterChain(HttpSecurity http,OpenIdentitySpnegoAuthenticationFilter f)throws Exception{return http.csrf(c->c.disable()).authorizeHttpRequests(a->a.requestMatchers("/error").permitAll().anyRequest().authenticated()).addFilterAfter(f,SecurityContextHolderFilter.class).build();}
 private static String required(String v,String n){if(v==null||v.isBlank())throw new IllegalStateException("missing openidentity.active-directory."+n);return v;}
}