server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          openidentity:
            provider: openidentity
            client-id: openidentity-reference-client
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
        provider:
          openidentity:
            issuer-uri: http://127.0.0.1:9000

server:
  error:
    include-exception: true
    include-message: always
