#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
v=json.loads((ROOT/"test-vectors/external-ad-binding-v1-pre-freeze.json").read_text())
expected={
"AD01":"OK","AD02":"OK","AD03":"OK","AD04":"OK","AD05":"OK",
"ADI01":"BINDING_NOT_FOUND","ADI02":"BINDING_NOT_FOUND","ADI03":"BINDING_NOT_FOUND","ADI04":"BINDING_NOT_FOUND","ADI05":"BINDING_NOT_FOUND",
"ADI06":"AD_DIRECTORY_UNTRUSTED","ADI07":"AD_SERVICE_NOT_ALLOWED","ADI08":"AD_AUTH_MECHANISM_NOT_ALLOWED","ADI09":"AD_CHANNEL_UNTRUSTED","ADI10":"AD_ACCOUNT_UNUSABLE",
"ADI11":"BINDING_AUTHORIZATION_INVALID","ADI12":"BINDING_CONTEXT_MISMATCH","ADI13":"BINDING_CONTEXT_MISMATCH","ADI14":"BINDING_CONTEXT_MISMATCH","ADI15":"BINDING_CONTEXT_MISMATCH",
"ADI16":"BINDING_CONFLICT","ADI17":"BINDING_REVOKED","ADI18":"BINDING_GENERATION_STALE","ADI19":"IDENTITY_INACTIVE","ADI20":"BINDING_EXPIRED",
"ADI21":"BINDING_CHALLENGE_INVALID","ADI22":"BINDING_REPLAY","ADI23":"BINDING_AUTHORIZATION_INVALID","ADI24":"BINDING_AUTHORIZATION_INVALID","ADI25":"BINDING_CONTEXT_MISMATCH",
"ADI26":"ASSURANCE_INSUFFICIENT","ADI27":"BINDING_ID_MISMATCH","ADI28":"AD_PRINCIPAL_INVALID","ADI29":"AD_PRINCIPAL_INVALID","ADI30":"AD_PRINCIPAL_INVALID"}
rows=v["semanticVectors"]; assert len(rows)==35
seen=set()
for x in rows:
 assert x["id"] not in seen;seen.add(x["id"])
 assert expected[x["id"]]==x["expected"]
 assert x["valid"]==(x["expected"]=="OK")
print("35 AD PRE-FREEZE SEMANTIC CONTRACTS VERIFIED")
