package org.openidentity.ad;

import org.openidentity.cbor.*;
import java.security.*;import java.util.*;

public final class ExternalAdBindingV1 {
 public static final int VERSION=1,BIND=1,REVOKE=2,KERBEROS_SPNEGO=1,LDAP_SASL_SIGNED=2,LDAP_TLS_SIMPLE_WITH_CHANNEL_BINDING=3;
 private static final String DOMAIN="OpenIdentity External Active Directory Binding";
 private ExternalAdBindingV1(){}
 public record Binding(byte[] identity,byte[] directoryId,byte[] objectGuid,String serviceId,long createdAt,Long expiresAt,long authenticationGeneration){
  public Binding{identity=copy(identity,32,"identity");directoryId=copy(directoryId,16,"directoryId");objectGuid=copy(objectGuid,16,"objectGuid");Objects.requireNonNull(serviceId);if(serviceId.isEmpty()||serviceId.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>2048)throw new IllegalArgumentException("serviceId");if(createdAt<0||authenticationGeneration<0||(expiresAt!=null&&expiresAt<0))throw new IllegalArgumentException("uint64");}
  @Override public byte[] identity(){return identity.clone();}@Override public byte[] directoryId(){return directoryId.clone();}@Override public byte[] objectGuid(){return objectGuid.clone();}
 }
 public static byte[] encode(Binding b){var w=new DeterministicCborWriter();w.writeMapHeader(8);u(w,1);u(w,1);u(w,2);w.writeByteString(b.identity());u(w,3);w.writeByteString(b.directoryId());u(w,4);w.writeByteString(b.objectGuid());u(w,5);w.writeTextString(b.serviceId());u(w,6);u(w,b.createdAt());u(w,7);if(b.expiresAt()==null)w.writeNull();else u(w,b.expiresAt());u(w,8);u(w,b.authenticationGeneration());return w.toByteArray();}
 public static Binding decode(byte[] bytes){try{var r=new StrictCborReader(bytes);if(r.readMapHeader()!=8)throw new IllegalArgumentException("map");key(r,1);if(r.readUnsigned()!=1)throw new IllegalArgumentException("version");key(r,2);byte[] id=r.readByteString();key(r,3);byte[] dir=r.readByteString();key(r,4);byte[] guid=r.readByteString();key(r,5);String service=r.readTextString();key(r,6);long created=r.readUnsigned();key(r,7);Long expires;if(r.peekByte()==0xf6){r.readNull();expires=null;}else expires=r.readUnsigned();key(r,8);long gen=r.readUnsigned();if(!r.done())throw new IllegalArgumentException("trailing");var b=new Binding(id,dir,guid,service,created,expires,gen);if(!Arrays.equals(bytes,encode(b)))throw new IllegalArgumentException("non-deterministic");return b;}catch(RuntimeException e){throw new IllegalArgumentException("invalid binding bytes",e);}}
 public static byte[] bindingId(Binding b){byte[] bb=encode(b);var w=new DeterministicCborWriter();w.writeArrayHeader(3);w.writeTextString(DOMAIN);u(w,1);w.writeByteString(bb);return mh(w.toByteArray());}
 public static byte[] encodeContext(int action,Binding b,int mechanism,byte[] challenge,byte[] bindingId){if(action!=BIND&&action!=REVOKE)throw new IllegalArgumentException("action");if(mechanism<1||mechanism>3)throw new IllegalArgumentException("mechanism");if(challenge==null||challenge.length<16||challenge.length>128)throw new IllegalArgumentException("challenge");if(action==BIND&&bindingId!=null)throw new IllegalArgumentException("bind bindingId");if(action==REVOKE&&(bindingId==null||bindingId.length!=34))throw new IllegalArgumentException("revoke bindingId");var w=new DeterministicCborWriter();w.writeMapHeader(action==REVOKE?12:11);u(w,1);u(w,1);u(w,2);u(w,action);u(w,3);w.writeByteString(b.identity());u(w,4);w.writeByteString(b.directoryId());u(w,5);w.writeByteString(b.objectGuid());u(w,6);w.writeTextString(b.serviceId());u(w,7);u(w,mechanism);u(w,8);w.writeByteString(challenge);u(w,9);u(w,b.authenticationGeneration());u(w,10);u(w,b.createdAt());u(w,11);if(b.expiresAt()==null)w.writeNull();else u(w,b.expiresAt());if(action==REVOKE){u(w,12);w.writeByteString(bindingId);}return w.toByteArray();}
 public static byte[] contextHash(byte[] bytes){return mh(bytes);}
 private static byte[] copy(byte[] b,int n,String name){Objects.requireNonNull(b);if(b.length!=n)throw new IllegalArgumentException(name);return b.clone();}private static void key(StrictCborReader r,long n){if(r.readUnsigned()!=n)throw new IllegalArgumentException("map key");}private static void u(DeterministicCborWriter w,long n){w.writeUnsigned(n);}private static byte[] mh(byte[] in){try{byte[] d=MessageDigest.getInstance("SHA-256").digest(in),o=new byte[34];o[0]=0x12;o[1]=0x20;System.arraycopy(d,0,o,2,32);return o;}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}