package org.openidentity.oauth;
public enum ProfileError {
 INVALID_REQUEST, INVALID_TARGET, DPOP_REQUIRED, DPOP_CONTEXT_MISMATCH,
 DELEGATION_NOT_CURRENTLY_USABLE, DELEGATION_STATE_UNAVAILABLE,
 ACTOR_BINDING_MISMATCH, ASSERTION_CONTEXT_BINDING_MISMATCH,
 CAPABILITY_PROFILE_MAPPING_UNAVAILABLE, TARGET_SCOPE_PAIR_NOT_AUTHORIZED,
 ASSERTION_REPLAY, UNSUPPORTED_REQUESTED_TOKEN_TYPE
}
