package org.openidentity.core;

public enum VerificationError {
  INVALID_INPUT,
  STATE_UNAVAILABLE,
  NOT_CURRENTLY_USABLE,
  ACTOR_BINDING_MISMATCH,
  ASSERTION_CONTEXT_BINDING_MISMATCH,
  CAPABILITY_PROFILE_UNAVAILABLE,
  AUTHORITY_NOT_PERMITTED
}
